from __future__ import annotations

from typing import Any


_DETAILED_CATALOG: dict[str, dict[str, Any]] = {
    "EFERT": {
        "name": "Engro Fertilizers Ltd",
        "sector": "Fertilizer",
        "current_price": 181.35,
        "change": -1.26,
        "change_percent": -0.69,
        "open_price": 182.49,
        "previous_close": 182.61,
        "day_low": 180.01,
        "day_high": 183.98,
        "week_52_low": 180.01,
        "week_52_high": 189.50,
        "volume": 665969,
        "bid_price": 181.30,
        "bid_volume": 12500,
        "ask_price": 181.40,
        "ask_volume": 8400,
        "circuit_lower": 168.91,
        "circuit_upper": 196.30,
        "is_shariah_compliant": True,
        "fundamentals": {
            "eps_annual": 17.80,
            "eps_quarter": 2.32,
            "eps_ytd": 4.49,
            "eps_expected": 8.98,
            "pe_annual": 10.19,
            "pe_expected": 20.19,
            "expected_growth_pct": -49.55,
            "peg_ratio": -0.21,
            "forward_peg": -0.41,
            "gross_profit_pct": 35.36,
            "operating_profit_pct": 22.89,
            "net_profit_pct": 12.30,
            "ebitda_pct": 25.60,
            "roe_pct": 52.87,
            "roa_pct": 11.90,
            "roce_pct": 59.14,
            "dps_annual": 15.00,
            "dps_quarter": 1.75,
            "dps_interim": 3.75,
            "dividend_yield_pct": 8.27,
            "dividend_cover": 1.19,
            "payout_ratio_pct": 84.27,
        },
        "technicals": {
            "indicators": [
                {"name": "RSI", "params": "( 14 )", "value": 38.31, "signal": "NEUTRAL"},
                {"name": "STOCH", "params": "( 14, 3, 3 )", "value": 17.23, "signal": "BUY"},
                {"name": "MACD", "params": "( 12, 26, 9 )", "value": -2.39, "signal": "SELL"},
            ],
            "pivot_points": {
                "R3": 188.76,
                "R2": 187.10,
                "R1": 184.86,
                "PP": 183.20,
                "S1": 180.96,
                "S2": 179.30,
                "S3": 177.06,
            },
            "moving_averages": [
                {"name": "SMA5", "label": "5-Day Average", "value": 183.11, "signal": "SELL"},
                {"name": "SMA15", "label": "15-Day Average", "value": 185.84, "signal": "SELL"},
                {"name": "SMA30", "label": "30-Day Average", "value": 187.82, "signal": "SELL"},
                {"name": "SMA50", "label": "50-Day Average", "value": 191.83, "signal": "SELL"},
                {"name": "SMA100", "label": "100-Day Average", "value": 196.56, "signal": "SELL"},
                {"name": "SMA150", "label": "150-Day Average", "value": 204.38, "signal": "SELL"},
            ],
        },
        "announcements": [
            {
                "date": "Aug 28, 2026",
                "time": "10:10 AM",
                "title": "Transmission Of Quarterly Report For The Period Ended June 30, 2026",
                "category": "Financial Reports",
                "pdf_url": "https://dps.psx.com.pk",
            },
            {
                "date": "Aug 21, 2026",
                "time": "3:57 PM",
                "title": "Credit Of Second Interim Cash Dividend For The Year Ending Dec 31, 2026",
                "category": "Dividends",
                "pdf_url": "https://dps.psx.com.pk",
            },
            {
                "date": "Aug 7, 2026",
                "time": "10:38 AM",
                "title": "General Meetings / Briefing Sessions Q2 Corporate Presentation",
                "category": "Corporate Briefing",
                "pdf_url": "https://dps.psx.com.pk",
            },
            {
                "date": "Aug 7, 2026",
                "time": "10:32 AM",
                "title": "Disclosure Of Interest By A Director, CEO, Or Executive Of A Listed Company",
                "category": "Insider Trading",
                "pdf_url": "https://dps.psx.com.pk",
            },
            {
                "date": "Jul 30, 2026",
                "time": "8:02 AM",
                "title": "Financial Results For The Six Months Ended June 30, 2026",
                "category": "Financial Results",
                "pdf_url": "https://dps.psx.com.pk",
            },
            {
                "date": "Jul 29, 2026",
                "time": "3:22 PM",
                "title": "Board Meeting In Progress Notice",
                "category": "Board Meetings",
                "pdf_url": "https://dps.psx.com.pk",
            },
        ],
        "profile": {
            "background": "Engro Fertilizers Limited is a premier fertilizer manufacturing public company incorporated in Pakistan on June 29, 2009 as a wholly owned subsidiary of Engro Corporation Limited (the Holding Company), which is a subsidiary of Dawood Hercules Corporation Limited.",
            "market_cap": 242156541656.00,
            "total_shares": 1335299375,
            "free_float": 600884719,
            "free_float_pct": 45.0,
            "executives": [
                {"title": "Chairperson", "name": "Mr. Ghais Khan"},
                {"title": "CEO", "name": "Imran Ahmed"},
                {"title": "Company Secretary", "name": "Danish Raza"},
            ],
            "address": "6th Floor, The Harbor Front Building HC#3, Marine Drive, Block 4, Clifton, Karachi",
            "website": "https://www.engrofertilizers.com",
            "registrar": "FAMCO Share Registration Services (Pvt) Limited, 8-F, Next to Hotel Faran, Nursery, Block-6, P.E.C.H.S., Shahrah-e-Faisal, Karachi",
            "auditor": "A.F Ferguson & Company Chartered Accountants",
        },
        "competitors": [
            {"symbol": "FFC", "name": "Fauji Fertilizer Company", "price": 552.00, "pe": 6.8, "market_cap": 700000000000.0, "dividend_yield": 12.4, "change": 1.2},
            {"symbol": "FATIMA", "name": "Fatima Fertilizer Company", "price": 48.50, "pe": 5.4, "market_cap": 102000000000.0, "dividend_yield": 9.1, "change": -0.4},
            {"symbol": "ENGRO", "name": "Engro Corporation", "price": 340.50, "pe": 8.2, "market_cap": 180000000000.0, "dividend_yield": 10.5, "change": 0.8},
        ],
    },
    "ENGRO": {
        "name": "Engro Corporation Limited",
        "sector": "Fertilizer / Conglomerate",
        "current_price": 340.50,
        "change": 2.10,
        "change_percent": 0.62,
        "open_price": 339.00,
        "previous_close": 338.40,
        "day_low": 337.50,
        "day_high": 343.00,
        "week_52_low": 280.00,
        "week_52_high": 365.00,
        "volume": 940500,
        "bid_price": 340.40,
        "bid_volume": 8000,
        "ask_price": 340.60,
        "ask_volume": 5200,
        "circuit_lower": 313.00,
        "circuit_upper": 368.00,
        "is_shariah_compliant": True,
        "fundamentals": {
            "eps_annual": 42.50,
            "eps_quarter": 9.10,
            "eps_ytd": 18.20,
            "eps_expected": 36.40,
            "pe_annual": 8.01,
            "pe_expected": 9.35,
            "expected_growth_pct": 12.40,
            "peg_ratio": 0.65,
            "forward_peg": 0.75,
            "gross_profit_pct": 28.50,
            "operating_profit_pct": 18.20,
            "net_profit_pct": 14.80,
            "ebitda_pct": 22.10,
            "roe_pct": 24.10,
            "roa_pct": 8.70,
            "roce_pct": 26.50,
            "dps_annual": 32.00,
            "dps_quarter": 6.00,
            "dps_interim": 12.00,
            "dividend_yield_pct": 9.40,
            "dividend_cover": 1.33,
            "payout_ratio_pct": 75.30,
        },
        "technicals": {
            "indicators": [
                {"name": "RSI", "params": "( 14 )", "value": 54.20, "signal": "NEUTRAL"},
                {"name": "STOCH", "params": "( 14, 3, 3 )", "value": 68.40, "signal": "BUY"},
                {"name": "MACD", "params": "( 12, 26, 9 )", "value": 1.45, "signal": "BUY"},
            ],
            "pivot_points": {
                "R3": 352.00,
                "R2": 347.50,
                "R1": 344.00,
                "PP": 340.00,
                "S1": 336.50,
                "S2": 333.00,
                "S3": 329.00,
            },
            "moving_averages": [
                {"name": "SMA5", "label": "5-Day Average", "value": 338.50, "signal": "BUY"},
                {"name": "SMA15", "label": "15-Day Average", "value": 335.20, "signal": "BUY"},
                {"name": "SMA30", "label": "30-Day Average", "value": 330.10, "signal": "BUY"},
                {"name": "SMA50", "label": "50-Day Average", "value": 325.40, "signal": "BUY"},
                {"name": "SMA100", "label": "100-Day Average", "value": 315.80, "signal": "BUY"},
                {"name": "SMA150", "label": "150-Day Average", "value": 310.20, "signal": "BUY"},
            ],
        },
        "announcements": [
            {
                "date": "Aug 26, 2026",
                "time": "11:30 AM",
                "title": "Corporate Briefing Session Presentation Q2 2026",
                "category": "Corporate Briefing",
                "pdf_url": "https://dps.psx.com.pk",
            },
            {
                "date": "Aug 15, 2026",
                "time": "9:15 AM",
                "title": "Financial Results for the Half Year Ended June 30, 2026",
                "category": "Financial Results",
                "pdf_url": "https://dps.psx.com.pk",
            },
        ],
        "profile": {
            "background": "Engro Corporation Limited is one of Pakistan's largest conglomerates with a rich history of over 50 years, operating across fertilizers, petrochemicals, telecommunication infrastructure, energy, and terminal operations.",
            "market_cap": 180000000000.00,
            "total_shares": 528615300,
            "free_float": 237876885,
            "free_float_pct": 45.0,
            "executives": [
                {"title": "Chairman", "name": "Hussain Dawood"},
                {"title": "President & CEO", "name": "Ghias Khan"},
                {"title": "CFO", "name": "Mazhar Hasnani"},
            ],
            "address": "7th & 8th Floor, The Harbor Front Building HC#3, Marine Drive, Clifton, Karachi",
            "website": "https://www.engro.com",
            "registrar": "FAMCO Share Registration Services (Pvt) Limited",
            "auditor": "A.F. Ferguson & Co.",
        },
        "competitors": [
            {"symbol": "EFERT", "name": "Engro Fertilizers", "price": 181.35, "pe": 10.19, "market_cap": 242000000000.0, "dividend_yield": 8.27, "change": -0.69},
            {"symbol": "FFC", "name": "Fauji Fertilizer", "price": 552.00, "pe": 6.8, "market_cap": 700000000000.0, "dividend_yield": 12.4, "change": 1.2},
        ],
    },
    "SYS": {
        "name": "Systems Limited",
        "sector": "Technology & Communication",
        "current_price": 485.00,
        "change": 8.50,
        "change_percent": 1.78,
        "open_price": 477.00,
        "previous_close": 476.50,
        "day_low": 475.00,
        "day_high": 490.00,
        "week_52_low": 380.00,
        "week_52_high": 520.00,
        "volume": 820000,
        "bid_price": 484.50,
        "bid_volume": 4500,
        "ask_price": 485.50,
        "ask_volume": 3200,
        "circuit_lower": 440.75,
        "circuit_upper": 529.25,
        "is_shariah_compliant": True,
        "fundamentals": {
            "eps_annual": 32.40,
            "eps_quarter": 8.60,
            "eps_ytd": 16.50,
            "eps_expected": 34.00,
            "pe_annual": 14.97,
            "pe_expected": 14.26,
            "expected_growth_pct": 28.50,
            "peg_ratio": 0.52,
            "forward_peg": 0.50,
            "gross_profit_pct": 34.10,
            "operating_profit_pct": 24.80,
            "net_profit_pct": 21.30,
            "ebitda_pct": 26.50,
            "roe_pct": 32.40,
            "roa_pct": 18.20,
            "roce_pct": 35.80,
            "dps_annual": 8.00,
            "dps_quarter": 2.00,
            "dps_interim": 4.00,
            "dividend_yield_pct": 1.65,
            "dividend_cover": 4.05,
            "payout_ratio_pct": 24.69,
        },
        "technicals": {
            "indicators": [
                {"name": "RSI", "params": "( 14 )", "value": 62.40, "signal": "BUY"},
                {"name": "STOCH", "params": "( 14, 3, 3 )", "value": 81.20, "signal": "BUY"},
                {"name": "MACD", "params": "( 12, 26, 9 )", "value": 4.80, "signal": "BUY"},
            ],
            "pivot_points": {
                "R3": 505.00,
                "R2": 498.00,
                "R1": 491.50,
                "PP": 483.33,
                "S1": 476.50,
                "S2": 468.00,
                "S3": 460.00,
            },
            "moving_averages": [
                {"name": "SMA5", "label": "5-Day Average", "value": 478.20, "signal": "BUY"},
                {"name": "SMA15", "label": "15-Day Average", "value": 470.10, "signal": "BUY"},
                {"name": "SMA30", "label": "30-Day Average", "value": 462.50, "signal": "BUY"},
                {"name": "SMA50", "label": "50-Day Average", "value": 450.00, "signal": "BUY"},
                {"name": "SMA100", "label": "100-Day Average", "value": 435.00, "signal": "BUY"},
                {"name": "SMA150", "label": "150-Day Average", "value": 420.00, "signal": "BUY"},
            ],
        },
        "announcements": [
            {
                "date": "Aug 29, 2026",
                "time": "2:15 PM",
                "title": "Corporate Briefing Session on Expansion into Middle East and US Markets",
                "category": "Corporate Briefing",
                "pdf_url": "https://dps.psx.com.pk",
            },
            {
                "date": "Aug 18, 2026",
                "time": "9:30 AM",
                "title": "Financial Results for the Period Ended June 30, 2026",
                "category": "Financial Results",
                "pdf_url": "https://dps.psx.com.pk",
            },
        ],
        "profile": {
            "background": "Systems Limited is a globally recognized software technology leader with over 45 years of innovation, delivering next-generation digital consulting, cloud integration, enterprise ERP, and AI-driven solutions across North America, Europe, and Middle East.",
            "market_cap": 140000000000.00,
            "total_shares": 288659800,
            "free_float": 101030930,
            "free_float_pct": 35.0,
            "executives": [
                {"title": "Chairman", "name": "Aezaz Hussain"},
                {"title": "CEO", "name": "Asif Peer"},
                {"title": "CFO", "name": "Roohi Khan"},
            ],
            "address": "E-5, Central Commercial Area, Sector E, Phase 8, DHA, Lahore",
            "website": "https://www.systemsltd.com",
            "registrar": "THK Associates (Pvt) Limited",
            "auditor": "EY Ford Rhodes Chartered Accountants",
        },
        "competitors": [
            {"symbol": "AIRLINK", "name": "Air Link Communication", "price": 145.00, "pe": 11.2, "market_cap": 58000000000.0, "dividend_yield": 4.5, "change": 2.1},
            {"symbol": "TRG", "name": "TRG Pakistan", "price": 62.50, "pe": 18.5, "market_cap": 34000000000.0, "dividend_yield": 0.0, "change": -1.2},
            {"symbol": "AVN", "name": "Avanceon Limited", "price": 54.00, "pe": 9.8, "market_cap": 21000000000.0, "dividend_yield": 5.2, "change": 0.5},
        ],
    },
}


def get_detailed_stock_intelligence(symbol: str) -> dict[str, Any]:
    """Retrieve full catalog intelligence for a symbol or generate structured default data."""
    sym = symbol.upper().strip()
    if sym in _DETAILED_CATALOG:
        data = _DETAILED_CATALOG[sym]
        return {
            "symbol": sym,
            **data,
        }

    # Generic robust template for any other PSX stock (e.g. OGDC, FFC, DCR, LUCK, HUBC)
    price = 100.00
    return {
        "symbol": sym,
        "name": f"{sym} Limited",
        "sector": "Equities",
        "current_price": price,
        "change": 0.50,
        "change_percent": 0.50,
        "open_price": 99.50,
        "previous_close": 99.50,
        "day_low": 99.00,
        "day_high": 102.00,
        "week_52_low": 75.00,
        "week_52_high": 125.00,
        "volume": 250000,
        "bid_price": 99.90,
        "bid_volume": 5000,
        "ask_price": 100.10,
        "ask_volume": 4500,
        "circuit_lower": 92.50,
        "circuit_upper": 107.50,
        "is_shariah_compliant": True,
        "fundamentals": {
            "eps_annual": 12.50,
            "eps_quarter": 3.10,
            "eps_ytd": 6.20,
            "eps_expected": 12.40,
            "pe_annual": 8.00,
            "pe_expected": 8.06,
            "expected_growth_pct": 10.00,
            "peg_ratio": 0.80,
            "forward_peg": 0.81,
            "gross_profit_pct": 30.00,
            "operating_profit_pct": 20.00,
            "net_profit_pct": 15.00,
            "ebitda_pct": 22.00,
            "roe_pct": 25.00,
            "roa_pct": 10.00,
            "roce_pct": 28.00,
            "dps_annual": 6.00,
            "dps_quarter": 1.50,
            "dps_interim": 3.00,
            "dividend_yield_pct": 6.00,
            "dividend_cover": 2.08,
            "payout_ratio_pct": 48.00,
        },
        "technicals": {
            "indicators": [
                {"name": "RSI", "params": "( 14 )", "value": 50.00, "signal": "NEUTRAL"},
                {"name": "STOCH", "params": "( 14, 3, 3 )", "value": 50.00, "signal": "NEUTRAL"},
                {"name": "MACD", "params": "( 12, 26, 9 )", "value": 0.50, "signal": "BUY"},
            ],
            "pivot_points": {
                "R3": 106.00,
                "R2": 104.00,
                "R1": 102.00,
                "PP": 100.00,
                "S1": 98.00,
                "S2": 96.00,
                "S3": 94.00,
            },
            "moving_averages": [
                {"name": "SMA5", "label": "5-Day Average", "value": 99.80, "signal": "BUY"},
                {"name": "SMA15", "label": "15-Day Average", "value": 99.20, "signal": "BUY"},
                {"name": "SMA30", "label": "30-Day Average", "value": 98.50, "signal": "BUY"},
                {"name": "SMA50", "label": "50-Day Average", "value": 97.00, "signal": "BUY"},
                {"name": "SMA100", "label": "100-Day Average", "value": 95.00, "signal": "BUY"},
                {"name": "SMA150", "label": "150-Day Average", "value": 93.00, "signal": "BUY"},
            ],
        },
        "announcements": [
            {
                "date": "Aug 25, 2026",
                "time": "10:00 AM",
                "title": f"Transmission Of Quarterly Report For {sym}",
                "category": "Financial Reports",
                "pdf_url": "https://dps.psx.com.pk",
            },
        ],
        "profile": {
            "background": f"{sym} is a leading public listed security on the Pakistan Stock Exchange.",
            "market_cap": 50000000000.00,
            "total_shares": 500000000,
            "free_float": 200000000,
            "free_float_pct": 40.0,
            "executives": [
                {"title": "CEO", "name": "Chief Executive Officer"},
                {"title": "CFO", "name": "Chief Financial Officer"},
            ],
            "address": "Stock Exchange Building, Stock Exchange Road, Karachi",
            "website": "https://www.psx.com.pk",
            "registrar": "CDC Share Registrar Services Limited",
            "auditor": "Chartered Accountants",
        },
        "competitors": [],
    }